### ISSUE TITLE
How can I access the 100 classes of face images in VGGFace2?

### ISSUE THREAD

**Issue by Cassiatora** [shinington/facesec#1]

**Comment by Cassiatora** [comment]
I want to use the 100 classes of face images in VGGFace2 to train a model. So how can I access the 100 classes of face images in VGGFace2?

**Comment by shinington** [comment]
Unfortunately, VGGFace2 is no longer available to download from its official website. One option is that you can download the model already trained, by following the instruction [here](https://github.com/shinington/facesec/tree/master/model).
